name: Build ShitSID

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore Packages
      run: nuget restore ShitSID.sln

    - name: Build solution
      run: msbuild ShitSID.sln -t:rebuild -property:Configuration=Release -property:Platform="Any CPU"
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win-x64
        path: ShitSID\bin\Release\net9.0-windows
